image: Visual Studio 2017

configuration:
  - Debug
  
clone_folder: c:\projects\sc

platform:
- x86
- x64

install:
- ps: >-
    If ($env:Platform -Match "x86") {
      $env:CMAKE_ARCH=""
    } Else {
      $env:CMAKE_ARCH=" Win64"
    }
    
  - cd c:\projects\sc
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017%CMAKE_ARCH%" ..

build_script:
  - cmake --build .
